### ISSUE TITLE
creating new CTS256A-AL2

### ISSUE THREAD

**Issue by lynchaj** [GmEsoft/CTS256A-AL2#1]
Hi
Is it possible to get a blank NOS PIC7041 and use the files in this GitHub repository to program it so that it behaves like a CTS256A-AL2?

Is the PIC7041 field programmable?  I have read the CTS2056A-AL2 is a PIC7041 with its internal 4K ROM mask programmed at the factory.  Is it possible to start with a blank PIC7041 and program it yourself?  I presume the PIC7041 is an OTP ROM but not sure.

If I could make my own CTS256A-AL2 chip using a blank NOS PIC7041 chip that would relieve the difficulty in getting CTS256A-AL2 parts.

Thanks

**Comment by GmEsoft** [comment]
Hi,

Unfortunately I don't have the answer to your question. There may be programmable versions of that cpu. The CTS256A-AL2 was mask-programmed.

Another solution would be to emulate that chip using an ESP32 or something like that. Maybe I'll start such a project.

Cheers.

**Comment by lynchaj** [comment]
Hi

Thanks!  Cool project and thank you for posting this information

I have no doubt that functionally replacing the CTS256A-AL2 with another MCU or CPU is possible and I think it has been done already.  

What I think would be helpful would be a replacement for the CTS256A-AL2 that is pin compatible and could be used in legacy circuits.  I think a 5V tolerant MCU on a DIP-40 mini-PCB could pull off such a feat.  Better yet if it were able to execute the original TMS7041 code from the CTS256A-AL2 internal ROM.  That would mean an emulator running on the MCU to execute TMS7000 code.  

Here is a thread on retrobrewcomputers.org you might be interested in reading

https://www.retrobrewcomputers.org/forum/index.php?t=msg&th=759&start=0&

Thanks, Andrew Lynch

PS, I think I found the answer though.  I think the PIC7041/TMS7041 were most likely all mask programmed at the factory.  There are still variants around found in NOS stockpiles.  However, they seem to be application specific not field programmable like a modern MCU.  TI sold the SE70P161 prototyping device with a piggyback EPROM socket on its back for "field programmability".  Then when debugged, order many of the mask programmed MCUs from the factory.  Yikes, that was some tough turnaround time!

**Comment by lynchaj** [comment]
Hi
There are later versions of the PIC/TMS microcontroller which may serve as suitable for the CTS256 software such as the TMS77C82.  Not sure which programmers support these microcontrollers but it may be possible to program one of these to make a replica CTS256

https://www.utsource.net/sch/TMS77C82.html

**Comment by lynchaj** [comment]
Hi
I've had an idea of how to replace the hard to get and expensive CTS256 with a much less expensive alternative using similar, comparable parts (no exotic FPGAs, controllers, etc.) I would like to contact you but have no email for you and cannot find a way to direct message you on GitHub. Would you please contact me on GitHub or send me an email at

L Y N C H A J .at. Y A H O O .dot. C O M

Or you can reach me on retro-comp mailing list, retrobrewcomputers.org forum, or retrocomputingforum.com

Thank you! Andrew Lynch
